import { useState, type ReactNode } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Sparkles, RefreshCw, AlertTriangle, ArrowRight, Check, X, Loader2,
  Info, ShieldX, TrendingUp, Lightbulb,
} from 'lucide-react';

/**
 * AIInsight — the family of reusable AI surfaces used everywhere in Robin.
 *
 * RULE: AI is embedded INSIDE the workflow, not pinned to a chat bubble.
 * Every variant here is small, dismissable, and renders inline beside the
 * data it talks about. None of these open modals or steal focus.
 *
 * Variants:
 *   • AIInsight.Summary       — short AI-generated paragraph + regenerate
 *   • AIInsight.Recommendation— inline "you should do X" with accept/dismiss
 *   • AIInsight.Warning       — proactive risk surface (delay / blocker / anomaly)
 *   • AIInsight.Badge         — tiny "AI" chip — used inline next to predicted values
 *   • AIInsight.Stat          — KPI block with AI-derived value + caveat
 *   • AIInsight.Skeleton      — loading state mirroring final size
 *
 * Every variant accepts:
 *   - aiUsed?: boolean — when false (heuristic fallback), badge becomes "auto"
 *                       so users know this wasn't a model call. Honest.
 *   - confidence?: 'high' | 'medium' | 'low' — sets a small tint dot.
 *
 * Color is Forest Clay primary by default; warnings use destructive token.
 */

// ─── Shared bits ──────────────────────────────────────────────────────────

type Confidence = 'high' | 'medium' | 'low';

function ConfidenceDot({ c }: { c?: Confidence }) {
  if (!c) return null;
  const cls =
    c === 'high'   ? 'bg-emerald-500' :
    c === 'medium' ? 'bg-amber-500'   :
                     'bg-rose-500';
  return <span className={`h-1.5 w-1.5 rounded-full ${cls} shrink-0`} title={`${c} confidence`} />;
}

function SourceBadge({ aiUsed }: { aiUsed?: boolean }) {
  if (aiUsed === false) {
    return (
      <span
        className="inline-flex items-center gap-1 px-1 h-[15px] rounded text-[9px] uppercase tracking-wider font-bold text-muted-foreground bg-muted/80 border border-border"
        title="Computed from project data — no AI call was made for this insight."
      >
        auto
      </span>
    );
  }
  return (
    <span
      className="inline-flex items-center gap-1 px-1 h-[15px] rounded text-[9px] uppercase tracking-wider font-bold text-primary bg-primary/12 border border-primary/25"
      title="Generated by AI — may be wrong. Verify before acting."
    >
      <Sparkles className="h-2 w-2" /> AI
    </span>
  );
}

// ─── Summary — short paragraph + regenerate ───────────────────────────────

interface SummaryProps {
  text?: string;
  loading?: boolean;
  error?: string | null;
  onRegenerate?: () => void;
  onDismiss?: () => void;
  /** Label for the strip's section. */
  label?: string;
  aiUsed?: boolean;
  confidence?: Confidence;
  /** Short heuristic line shown when `text` is empty AND loading is false. */
  placeholder?: string;
}

function Summary({
  text, loading, error, onRegenerate, onDismiss,
  label = 'AI summary', aiUsed, confidence, placeholder,
}: SummaryProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: -2 }} animate={{ opacity: 1, y: 0 }}
      className="rounded-lg border border-primary/20 bg-primary/[0.04] px-3 py-2 space-y-1.5"
    >
      <div className="flex items-center gap-1.5">
        <Sparkles className="h-3 w-3 text-primary" />
        <p className="text-[10.5px] uppercase tracking-[0.16em] font-bold text-primary/85">{label}</p>
        <SourceBadge aiUsed={aiUsed} />
        <ConfidenceDot c={confidence} />
        <div className="ml-auto flex items-center gap-0.5">
          {onRegenerate && (
            <button
              onClick={onRegenerate}
              disabled={loading}
              className="h-5 w-5 rounded text-muted-foreground hover:text-primary hover:bg-primary/10 flex items-center justify-center disabled:opacity-50"
              title="Regenerate"
            >
              {loading ? <Loader2 className="h-3 w-3 animate-spin" /> : <RefreshCw className="h-3 w-3" />}
            </button>
          )}
          {onDismiss && (
            <button
              onClick={onDismiss}
              className="h-5 w-5 rounded text-muted-foreground hover:text-foreground hover:bg-muted flex items-center justify-center"
              title="Dismiss"
            >
              <X className="h-3 w-3" />
            </button>
          )}
        </div>
      </div>
      {error ? (
        <p className="text-[11.5px] text-rose-700 leading-snug">{error}</p>
      ) : loading && !text ? (
        <div className="space-y-1.5">
          <div className="h-2 rounded bg-muted-foreground/15 animate-pulse w-11/12" />
          <div className="h-2 rounded bg-muted-foreground/15 animate-pulse w-3/4" />
        </div>
      ) : text ? (
        <p className="text-[12.5px] leading-snug whitespace-pre-wrap">{text}</p>
      ) : (
        <p className="text-[11.5px] text-muted-foreground italic">{placeholder || 'No summary yet.'}</p>
      )}
    </motion.div>
  );
}

// ─── Recommendation — inline "do X" with accept/dismiss ───────────────────

interface RecommendationProps {
  text: string;
  /** Optional supporting reasoning shown below the text. */
  reason?: string;
  onAccept?: () => void;
  onDismiss?: () => void;
  accepting?: boolean;
  acceptLabel?: string;
  icon?: ReactNode;
  aiUsed?: boolean;
  confidence?: Confidence;
}

function Recommendation({
  text, reason, onAccept, onDismiss, accepting,
  acceptLabel = 'Do it', icon, aiUsed, confidence,
}: RecommendationProps) {
  return (
    <div className="rounded-lg border border-primary/20 bg-primary/[0.04] px-3 py-2 flex items-start gap-2">
      <div className="h-6 w-6 rounded-md bg-primary/15 text-primary flex items-center justify-center shrink-0">
        {icon || <Lightbulb className="h-3.5 w-3.5" />}
      </div>
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-1.5">
          <p className="text-[12.5px] font-semibold text-foreground leading-snug">{text}</p>
          <SourceBadge aiUsed={aiUsed} />
          <ConfidenceDot c={confidence} />
        </div>
        {reason && (
          <p className="text-[11px] text-muted-foreground mt-0.5 leading-snug">{reason}</p>
        )}
        {(onAccept || onDismiss) && (
          <div className="flex items-center gap-1.5 mt-1.5">
            {onAccept && (
              <button
                onClick={onAccept}
                disabled={accepting}
                className="inline-flex items-center gap-1 px-2 h-6 rounded-md bg-primary text-primary-foreground text-[11px] font-semibold hover:bg-primary/90 disabled:opacity-50"
              >
                {accepting ? <Loader2 className="h-3 w-3 animate-spin" /> : <Check className="h-3 w-3" />}
                {accepting ? 'Working…' : acceptLabel}
              </button>
            )}
            {onDismiss && (
              <button
                onClick={onDismiss}
                disabled={accepting}
                className="inline-flex items-center gap-1 px-2 h-6 rounded-md text-[11px] font-semibold text-muted-foreground hover:bg-muted hover:text-foreground disabled:opacity-50"
              >
                Dismiss
              </button>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// ─── Warning — proactive risk surface ─────────────────────────────────────

type WarningTone = 'danger' | 'warning' | 'info';

interface WarningProps {
  tone?: WarningTone;
  title: string;
  detail?: string;
  /** Inline action — usually "Open" or "Resolve". */
  action?: { label: string; onClick: () => void };
  onDismiss?: () => void;
  aiUsed?: boolean;
}

function Warning({
  tone = 'warning', title, detail, action, onDismiss, aiUsed,
}: WarningProps) {
  const cls = tone === 'danger'
    ? 'border-rose-500/25 bg-rose-500/[0.06] text-rose-700'
    : tone === 'info'
      ? 'border-blue-500/25 bg-blue-500/[0.06] text-blue-700'
      : 'border-amber-500/25 bg-amber-500/[0.06] text-amber-700';
  const Icon = tone === 'danger' ? ShieldX : tone === 'info' ? Info : AlertTriangle;
  return (
    <div className={`rounded-lg border px-3 py-2 flex items-start gap-2 ${cls}`}>
      <Icon className="h-3.5 w-3.5 mt-0.5 shrink-0" />
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-1.5">
          <p className="text-[12px] font-bold">{title}</p>
          <SourceBadge aiUsed={aiUsed} />
        </div>
        {detail && <p className="text-[11px] opacity-90 leading-snug mt-0.5">{detail}</p>}
      </div>
      {action && (
        <button
          onClick={action.onClick}
          className="shrink-0 inline-flex items-center gap-0.5 px-1.5 h-[20px] rounded text-[10.5px] font-bold hover:bg-current/10 transition-colors"
          style={{ background: 'rgba(0,0,0,0.04)' }}
        >
          {action.label} <ArrowRight className="h-2.5 w-2.5" />
        </button>
      )}
      {onDismiss && (
        <button
          onClick={onDismiss}
          className="shrink-0 h-5 w-5 rounded text-current opacity-70 hover:opacity-100 flex items-center justify-center"
          title="Dismiss"
        >
          <X className="h-3 w-3" />
        </button>
      )}
    </div>
  );
}

// ─── Badge — tiny inline "AI" / "auto" chip ───────────────────────────────

function Badge({ aiUsed, confidence, label }: { aiUsed?: boolean; confidence?: Confidence; label?: string }) {
  return (
    <span className="inline-flex items-center gap-1">
      <SourceBadge aiUsed={aiUsed} />
      <ConfidenceDot c={confidence} />
      {label && <span className="text-[10.5px] text-muted-foreground">{label}</span>}
    </span>
  );
}

// ─── Stat — KPI block where the value came from AI/heuristic ──────────────

interface StatProps {
  label: string;
  value: ReactNode;
  hint?: string;
  tone?: 'default' | 'success' | 'warning' | 'danger';
  aiUsed?: boolean;
  confidence?: Confidence;
  icon?: ReactNode;
}

function Stat({ label, value, hint, tone = 'default', aiUsed, confidence, icon }: StatProps) {
  const toneCls =
    tone === 'success' ? 'text-emerald-700' :
    tone === 'warning' ? 'text-amber-700'   :
    tone === 'danger'  ? 'text-rose-700'    :
                         'text-foreground';
  return (
    <div className="rounded-md bg-muted/30 px-3 py-2">
      <div className="flex items-center gap-1.5">
        {icon && <span className="text-muted-foreground">{icon}</span>}
        <p className="text-[10px] uppercase tracking-[0.14em] font-bold text-muted-foreground">{label}</p>
        <span className="ml-auto"><Badge aiUsed={aiUsed} confidence={confidence} /></span>
      </div>
      <p className={`text-[18px] font-bold tabular-nums leading-tight mt-0.5 ${toneCls}`}>{value}</p>
      {hint && <p className="text-[10.5px] text-muted-foreground">{hint}</p>}
    </div>
  );
}

// ─── Skeleton — preserves layout while a call is in flight ────────────────

function Skeleton({ lines = 2 }: { lines?: number }) {
  return (
    <div className="rounded-lg border border-primary/20 bg-primary/[0.04] px-3 py-2 space-y-1.5">
      <div className="flex items-center gap-1.5">
        <Sparkles className="h-3 w-3 text-primary/60" />
        <div className="h-2 w-20 rounded bg-muted-foreground/15 animate-pulse" />
      </div>
      {Array.from({ length: lines }).map((_, i) => (
        <div key={i} className={`h-2 rounded bg-muted-foreground/15 animate-pulse ${i % 2 ? 'w-3/4' : 'w-11/12'}`} />
      ))}
    </div>
  );
}

// ─── Dismissible wrapper — used to remember "user dismissed" per-key ──────

/**
 * Hook: useDismissedInsight(key)
 * Stores a per-key dismissal in localStorage so a one-off "Dismiss" doesn't
 * re-show the same recommendation on the next page load. Pass the key (e.g.
 * `wf:abc123:delay-warning`) and the component will read+write it.
 */
export function useDismissedInsight(key: string) {
  const storeKey = `robin.ai.dismissed.${key}`;
  const [dismissed, setDismissed] = useState<boolean>(() => {
    try { return localStorage.getItem(storeKey) === '1'; } catch { return false; }
  });
  return {
    dismissed,
    dismiss: () => {
      try { localStorage.setItem(storeKey, '1'); } catch {}
      setDismissed(true);
    },
    restore: () => {
      try { localStorage.removeItem(storeKey); } catch {}
      setDismissed(false);
    },
  };
}

// ─── Composite export — `<AIInsight.Summary />` style API ─────────────────

export const AIInsight = {
  Summary,
  Recommendation,
  Warning,
  Badge,
  Stat,
  Skeleton,
};

// Re-export icons commonly used alongside the family for caller convenience.
export { Sparkles as AIIcon, Lightbulb, TrendingUp, AnimatePresence };
