import { Schema, model, Types } from 'mongoose';

/**
 * MorningBrief — daily executive digest generated by Gemini at 8 AM IST.
 *
 * One document per (organization, IST-date). Re-running on the same day
 * upserts (so manual re-generation overwrites the cron-generated one).
 * The admin dashboard reads the latest brief per org and renders it as
 * a hero card.
 */
const MorningBriefSchema = new Schema({
  organizationId:    { type: Types.ObjectId, ref: 'Organization', required: true, index: true },
  // IST-day key, format YYYY-MM-DD. Indexed so per-day upsert is cheap.
  istDate:           { type: String, required: true, index: true },
  // AI-generated plain-text summary (bullet list).
  summary:           { type: String, default: '' },
  // The raw snapshot we fed to Gemini — kept for debugging / re-generation.
  snapshot:          { type: Schema.Types.Mixed, default: {} },
  generatedBy:       { type: String, enum: ['cron', 'manual'], default: 'cron' },
  aiUsed:            { type: Boolean, default: false },
}, { timestamps: true });

MorningBriefSchema.index({ organizationId: 1, istDate: -1 }, { unique: true });

export default model('MorningBrief', MorningBriefSchema);
